# Generated by Django 5.2.7 on 2025-10-22 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=100)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('default_question_count', models.PositiveIntegerField(default=40)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='ExamChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.examquestion')),
            ],
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam_type',
            field=models.ForeignKey(help_text='Which exam type this question belongs to (e.g., Foundation, TTA)', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.examtype'),
        ),
        migrations.CreateModel(
            name='MockExamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('question_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_type', models.ForeignKey(help_text='Select which exam type this mock will simulate.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.examtype')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
