# Generated by Django 5.2.7 on 2025-10-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='answers',
            field=models.JSONField(default=[], help_text="List of correct labels, e.g. ['A'] or ['A', 'C']"),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='options',
            field=models.JSONField(default={}, help_text="JSON dict of options, e.g. {'A': 'Option 1', 'B': 'Option 2'}"),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.examtype'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_text',
            field=models.TextField(help_text='The main question text.'),
        ),
        migrations.AlterField(
            model_name='mockexampage',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.examtype'),
        ),
        migrations.DeleteModel(
            name='ExamChoice',
        ),
    ]
