# Generated by Django 5.2.7 on 2025-10-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_examquestion_answers_examquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='answers',
            field=models.JSONField(default=list, help_text="List of correct labels, e.g. ['A'] or ['A', 'C']"),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='options',
            field=models.JSONField(default=dict, help_text="JSON dict of options, e.g. {'A': 'Option 1', 'B': 'Option 2'}"),
        ),
    ]
