# Generated by Django 5.2.7 on 2025-10-18 14:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('bash', 'Bash')], 'help_text': 'Select the code language for syntax highlighting.'}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste your code snippet here.'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {})}),
        ),
    ]
