# Generated by Django 5.2.7 on 2025-10-18 17:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('code', 4), ('note', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('bash', 'Bash')], 'help_text': 'Select the code language for syntax highlighting.'}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste your code snippet here.'}), 4: ('wagtail.blocks.StructBlock', [[('language', 2), ('code', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the note', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('body', 6)]], {})}),
        ),
    ]
